### ISSUE TITLE
Isn't giving me a Nitro code even after 30k+ attempts

### ISSUE THREAD

**Issue by Xp10d3** [Bowlingtoolkit/Discord-Nitro-Gift-Brute-Force#1]
I don't know if this is just how it is or whether the method got patched, but after setting the threads to 1000 and retries or something to 10001, I got to 30,000+ attempts and I still didn't get a single hit. How long do I have to wait? Is this method patched? How do I get Nitro............................

**Comment by REVENGE977** [comment]
this method is so hard to get nitro with ,
the best method right now is using auto nitro claimer , simply it claims any nitro sends in any server
this is useful in drop servers .
